### ISSUE TITLE
T2V training and evaluation

### ISSUE THREAD

**Issue by yizenghan** [Vchitect/Latte#100]
Hi, will the training/evaluation code & dataset for T2V be released? That will benefit the fair comparison for academic use.

**Comment by maxin-cn** [comment]
The released paper Latte does not focus on assessing the quality of T2V generation. We will release the toy T2V training code after our paper is accepted. The datasets used by Latte T2V are publicly available.

**Comment by yizenghan** [comment]
Thanks for replying. To my understanding, Latte uses a subset of WebVid-10M + Vimeo25M. Could you provide more details about how this subset is constructed?

**Comment by maxin-cn** [comment]
In the training process, the sampling rate of both is 50%. So I can't say exactly which videos from both datasets are used.

**Comment by yizenghan** [comment]
Thanks! But if a full epoch is finished, all videos in both datasets are used. So do you mean that the training does not cover a complete epoch? If yes, I'm curious how many videos are used.

**Comment by maxin-cn** [comment]
The number of videos used in the first released T2V model is mentioned in the released paper, which should be about 330,000. I also need to check the number of videos used for Latte-1.

**Comment by yizenghan** [comment]
Thanks~
