### ISSUE TITLE
训练模型后的效果评估

### ISSUE THREAD

**Issue by hejiashuuu** [Vchitect/Latte#102]
请问我在使用您的代码训练之后怎么知道哪个检测点模型的效果最好？

**Comment by maxin-cn** [comment]
你可以在训练过程中写个validation，简单的验证下哪个模型最好

**Comment by hejiashuuu** [comment]
Can Senie use the same training code?

**Comment by maxin-cn** [comment]
> Can Senie use the same training code?

SEINE uses roughly the same training code as Latte.

**Comment by hejiashuuu** [comment]
Can you tell me some training details about SEINE please?I am training this model on a new dataset.

**Comment by maxin-cn** [comment]
Hi @hejiashuuu , SEINE was not trained by me directly, I suggest you go to SEINE's github repo for questions.
