### ISSUE TITLE
ImportError: cannot import name 'LattePipeline'

### ISSUE THREAD

**Issue by lxrswdd** [Vchitect/Latte#109]
My diffuser library info:
`diffusers                 0.24.0                   pypi_0    pypi`
```
{
	"name": "ImportError",
	"message": "cannot import name 'LattePipeline' from 'diffusers' (/home/assa8945/miniconda3/envs/latte/lib/python3.12/site-packages/diffusers/__init__.py)",
	"stack": "---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 from diffusers import LattePipeline
      2 from diffusers.models import AutoencoderKLTemporalDecoder
      3 from torchvision.utils import save_image

ImportError: cannot import name 'LattePipeline' from 'diffusers' (/home/assa8945/miniconda3/envs/latte/lib/python3.12/site-packages/diffusers/__init__.py)"
}```

**Comment by maxin-cn** [comment]
`LattePipeline` is added to the `diffusers` version [`0.30.0`](https://github.com/huggingface/diffusers/blob/8a79d8ec3973e78065f13638eefc0dc7d4dc6009/src/diffusers/__init__.py#L290).

**Comment by lxrswdd** [comment]
@maxin-cn 
Ok so the environment.yaml is outdated, we should manually upgrade `diffusers`?

`name: latte
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.10
  - pytorch > 2.0.0
  - torchvision
  - pytorch-cuda >= 11.7
  - pip:
    - timm
    - diffusers[torch]==0.24.0
    - accelerate
    - tensorboard
    - einops
    - transformers
    - av
    - scikit-image
    - decord
    - pandas
    - imageio-ffmpeg
    - sentencepiece
    - beautifulsoup4
    - ftfy
    - omegaconf`

**Comment by maxin-cn** [comment]
`environment.yaml` is not outdated; it supports the code in the repository. `LattePipeline` was added to `diffusers` later, and if you want to adopt `LattePipeline` for inference, you need to manually update the diffusers version.
