### ISSUE TITLE
Works.  But question:  Attributes passed, but not expected (LatteTransformer3DModel)

### ISSUE THREAD

**Issue by MarsThunder** [Vchitect/Latte#111]
Running quantized code for 9GB works fine. Console feedback before loading pipeline components says:   
"The config attributes {'attention_type': 'default', 'double_self_attention': False, 'norm_num_groups': 32, 'num_vector_embeds': None, 'only_cross_attention': False, 'upcast_attention': False, 'use_linear_projection': False} were passed to LatteTransformer3DModel, but are not expected and will be ignored. Please verify your config.json configuration file."

I checked config.json file in .cache folder and it does indeed have many of those attributes listed.  Just curious why that  message was produced.

**Comment by maxin-cn** [comment]
The information returned by the console is an unnecessary parameter in LatteTransformer3D. We will remove redundant parameters from `config.json`. Thank you for your feedback.
