### ISSUE TITLE
About dataset of pretrained T2V model

### ISSUE THREAD

**Issue by jang-1996** [Vchitect/Latte#113]
Hello, 
I have a question about details of dataset of your [pretrained T2V model](https://huggingface.co/maxin-cn/Latte-1/tree/main).

In the paper, you use the FaceForensics, SkyTimelapse, UCF101, and Taichi-HD datasets.
Did you use all of those datasets when training the T2V model you provide? Or what data set did you use?

Thank you.

**Comment by maxin-cn** [comment]
When we trained the Latte T2V model, we only used two datasets, webvideo10m and vimeo25m.

**Comment by jang-1996** [comment]
Thank you!
