### ISSUE TITLE
FVD of the Taichi checkpoint

### ISSUE THREAD

**Issue by yizenghan** [Vchitect/Latte#115]
Hi, I used your scripts (sample, convert, calc fvd) to test the performance of the released checkpoints. It comes out that the ucf checkpoint got ~190 fvd, the ffs.pt got ~30 fvd. I guess these two are reasonable. But the Taichi checkpoint only got ~170 fvd, which is significantly larger than your reported value in the paper (97.09).

**Comment by yizenghan** [comment]
I used the released taichi-hd.pt and vae in https://huggingface.co/maxin-cn/Latte/tree/main for testing.

**Comment by maxin-cn** [comment]
How do you process with the Taichi dataset?

**Comment by yizenghan** [comment]
I followed your guide at https://huggingface.co/datasets/maxin-cn/Taichi-HD. 
Now the structure is:
taichi-256/
  frames  
  syncRecord.txt  
  taichi_256_train.jsonl  
  train_list.txt  train_list_tmp.txt

I used taichi-256/frames/train for evaluation.

**Comment by yizenghan** [comment]
Ths disk used for taichi-256/frames is

7.0G    ./test
96G     ./train
102G    .

**Comment by maxin-cn** [comment]
I just checked the code that evaluates FVD on the Taichi dataset, and I set realdata_subsample_factor to 6. You can change it to this value and you should get a similar FVD value.

![image](https://github.com/user-attachments/assets/7c40bfe4-e06c-43da-ac1a-213f57679e3d)

**Comment by yizenghan** [comment]
Thanks, I wonder where I can set this hyper-param.

**Comment by maxin-cn** [comment]
Please see here https://github.com/Vchitect/Latte/blob/1b74d1e038b1a5a43c7fdaec94477831bc4cefb8/tools/metrics/frechet_video_distance.py#L18

**Comment by yizenghan** [comment]
Found it, thanks! For other datasets, how is this value set? Now I use the default 3 for FFS and UCF.

**Comment by maxin-cn** [comment]
Other datasets follow the default value.

**Comment by yizenghan** [comment]
Thanks again.

**Comment by xyniu1** [comment]
Hi, thanks for the great work!
I have a related question. I was able to reproduce the ~100 FVD for the Taichi dataset, but only when comparing with the train split (i.e. using videos from the train split as "real videos"). Once I compared with the test split, the FVD went beyond 400. Can you comment on this observation?
