### ISSUE TITLE
The resolution of T2V 

### ISSUE THREAD

**Issue by jang-1996** [Vchitect/Latte#118]
Hello.
I want to generate 256x256 videos by using [T2V model](https://huggingface.co/maxin-cn/Latte/tree/main).
So, I change the hyperparmeter image_size in t2v_sample.yaml.
However, I got strange videos. 
How can I get 256x256 videos?

Thanks

**Comment by maxin-cn** [comment]
The Latte T2V model is trained directly on 512*512. If you want to generate other resolutions of video, please watch our next post Latte-2.
