### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Taldhi** [Vchitect/Latte#12]
ImportError: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings' 
can anyone please help with this errror?

**Comment by maxin-cn** [comment]
> ImportError: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings' can anyone please help with this errror?

Maybe you can update the version of `diffusers` to `0.24.0` for text-to-video generation.

**Comment by Taldhi** [comment]
> > ImportError: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings' can anyone please help with this errror?
> 
> Maybe you can update the version of `diffusers` to `0.24.0` for text-to-video generation.

thanks that works .

**Comment by zgdjcls** [comment]
Hi, I've checked https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/embeddings.py, could we use PixArtAlphaTextProjection and PixArtAlphaCombinedTimestepSizeEmbeddings to replace CaptionProjection and CombinedTimestepSizeEmbeddings in your code? 
Also, the cudatoolkit is not written into enviroment.yml, could you please update the environment file or provide the version of cudatoolkit?

**Comment by maxin-cn** [comment]
> Hi, I've checked https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/embeddings.py, could we use PixArtAlphaTextProjection and PixArtAlphaCombinedTimestepSizeEmbeddings to replace CaptionProjection and CombinedTimestepSizeEmbeddings in your code? Also, the cudatoolkit is not written into enviroment.yml, could you please update the environment file or provide the version of cudatoolkit?

If you want to use `PixArtAlphaTextProjection` and `PixArtAlphaCombinedTimestepSizeEmbeddings` to replace `CaptionProjection` and `CombinedTimestepSizeEmbeddings` in my codes, please ensure the implementation of the both are consistent. 

 The version of  `cudatoolkit` for my `pytorch` (2.0.0) is 11.8.
