### ISSUE TITLE
How can i train Video VAE? 

### ISSUE THREAD

**Issue by whikwon** [Vchitect/Latte#120]
Thank you for sharing your excellent work. 
I'm considering training Latte using a medical dataset and wondering how I can train a video VAE for it.

**Comment by maxin-cn** [comment]
Thank you for your interest. We did not train VAE, we used the VAE model trained by Stable Diffusion and Stable Video Diffusion. You can start by examining the results of reconstructing your video using a pre-trained VAE model.

**Comment by whikwon** [comment]
Ah, I got it. Thanks!
