### ISSUE TITLE
FVD on UCF101

### ISSUE THREAD

**Issue by huangyf530** [Vchitect/Latte#123]
I evaluate the fvd value on UCF101 dataset with your pretrained model. But I get a FVD value of 168, which is far lower than your reported result. Is this result correct?
The model I used is https://huggingface.co/maxin-cn/Latte. And 2048 videos are sampled.

**Comment by maxin-cn** [comment]
That's correct. Please see this issue https://github.com/Vchitect/Latte/issues/115.

**Comment by huangyf530** [comment]
Oh, I see! Thank you for your response.
