### ISSUE TITLE
Asking for training code for t2v

### ISSUE THREAD

**Issue by Taldhi** [Vchitect/Latte#13]
I was trying to train for the text to video generation can you please provide any code base as in the train.py it is said that T2V training is not supported at this moment so how can I do that ?

**Comment by maxin-cn** [comment]
> I was trying to train for the text to video generation can you please provide any code base as in the train.py it is said that T2V training is not supported at this moment so how can I do that ?

We currently have no plans to release text-to-video training code. However, I think it should be relatively easy to change the text-to-video inference code to training code. You can refer to our `train.py`.
