### ISSUE TITLE
TypeError: PatchEmbed.__init__() got an unexpected keyword argument 'bias'

### ISSUE THREAD

**Issue by Xls1994** [Vchitect/Latte#19]
When I use the 
`bash sample/ffs.sh`
meets this error. 

Traceback (most recent call last):
  File "/app/alpaca-lora/voice/clip_proj/Latte/sample/sample.py", line 138, in <module>
    main(omega_conf)
  File "/app/alpaca-lora/voice/clip_proj/Latte/sample/sample.py", line 56, in main
    model = get_models(args).to(device)
  File "/app/alpaca-lora/voice/clip_proj/Latte/models/__init__.py", line 44, in get_models
    return Latte_models[args.model](
  File "/app/alpaca-lora/voice/clip_proj/Latte/models/latte.py", line 465, in Latte_XL_2
    return Latte(depth=28, hidden_size=1152, patch_size=2, num_heads=16, **kwargs)
  File "/app/alpaca-lora/voice/clip_proj/Latte/models/latte.py", line 233, in __init__
    self.x_embedder = PatchEmbed(input_size, patch_size, in_channels, hidden_size, bias=True)
TypeError: PatchEmbed.__init__() got an unexpected keyword argument 'bias'

**Comment by maxin-cn** [comment]
> When I use the `bash sample/ffs.sh` meets this error.
> 
> Traceback (most recent call last): File "/app/alpaca-lora/voice/clip_proj/Latte/sample/sample.py", line 138, in main(omega_conf) File "/app/alpaca-lora/voice/clip_proj/Latte/sample/sample.py", line 56, in main model = get_models(args).to(device) File "/app/alpaca-lora/voice/clip_proj/Latte/models/**init**.py", line 44, in get_models return Latte_models[args.model]( File "/app/alpaca-lora/voice/clip_proj/Latte/models/latte.py", line 465, in Latte_XL_2 return Latte(depth=28, hidden_size=1152, patch_size=2, num_heads=16, **kwargs) File "/app/alpaca-lora/voice/clip_proj/Latte/models/latte.py", line 233, in **init** self.x_embedder = PatchEmbed(input_size, patch_size, in_channels, hidden_size, bias=True) TypeError: PatchEmbed.**init**() got an unexpected keyword argument 'bias'

Hi, I just tested my code and did not encounter any errors. Could you please provide more details? Thanks~

**Comment by Xls1994** [comment]
> > When I use the `bash sample/ffs.sh` meets this error.
> > Traceback (most recent call last): File "/app/alpaca-lora/voice/clip_proj/Latte/sample/sample.py", line 138, in main(omega_conf) File "/app/alpaca-lora/voice/clip_proj/Latte/sample/sample.py", line 56, in main model = get_models(args).to(device) File "/app/alpaca-lora/voice/clip_proj/Latte/models/**init**.py", line 44, in get_models return Latte_models[args.model]( File "/app/alpaca-lora/voice/clip_proj/Latte/models/latte.py", line 465, in Latte_XL_2 return Latte(depth=28, hidden_size=1152, patch_size=2, num_heads=16, **kwargs) File "/app/alpaca-lora/voice/clip_proj/Latte/models/latte.py", line 233, in **init** self.x_embedder = PatchEmbed(input_size, patch_size, in_channels, hidden_size, bias=True) TypeError: PatchEmbed.**init**() got an unexpected keyword argument 'bias'
> 
> Hi, I just tested my code and did not encounter any errors. Could you please provide more details? Thanks~

Thanks, I find this error  is due to a version issue with the timm.  

When I uninstall the timm and install it again, the code works fine!
