### ISSUE TITLE
some error to save output text to video

### ISSUE THREAD

**Issue by trongnk2106** [Vchitect/Latte#22]
i have bug in line save video i have bug
 PyAVPlugin.write() got an unexpected keyword argument 'quality'
I cant save output

**Comment by maxin-cn** [comment]
> i have bug in line save video i have bug PyAVPlugin.write() got an unexpected keyword argument 'quality' I cant save output

Please run `pip install imageio-ffmpeg`.

**Comment by trongnk2106** [comment]
It work, thank you so much. Great!!
But when I change video_length prameter in t2v_sample.yaml from 16 to 32, its wrong :
 RuntimeError: The size of tensor a (32) must match the size of tensor b (16) at non-singleton dimension 1. 
How to make longer video

**Comment by maxin-cn** [comment]
> It work, thank you so much. Great!! But when I change video_length prameter in t2v_sample.yaml from 16 to 32, its wrong : RuntimeError: The size of tensor a (32) must match the size of tensor b (16) at non-singleton dimension 1. How to make longer video

I have updated the code to support video generation larger than 16 frames. Since our t2v model is trained on a 16-frame video dataset, direct generation of video larger than 16 frames will result in low-quality generated video results. We will release a long video generation model in the future.

**Comment by trongnk2106** [comment]
> > It work, thank you so much. Great!! But when I change video_length prameter in t2v_sample.yaml from 16 to 32, its wrong : RuntimeError: The size of tensor a (32) must match the size of tensor b (16) at non-singleton dimension 1. How to make longer video
> 
> I have updated the code to support video generation larger than 16 frames. Since our t2v model is trained on a 16-frame video dataset, direct generation of video larger than 16 frames will result in low-quality generated video results. We will release a long video generation model in the future.

Great! Can you give me the new inference for video generation large than 16 frames?

**Comment by maxin-cn** [comment]
> > > It work, thank you so much. Great!! But when I change video_length prameter in t2v_sample.yaml from 16 to 32, its wrong : RuntimeError: The size of tensor a (32) must match the size of tensor b (16) at non-singleton dimension 1. How to make longer video
> > 
> > 
> > I have updated the code to support video generation larger than 16 frames. Since our t2v model is trained on a 16-frame video dataset, direct generation of video larger than 16 frames will result in low-quality generated video results. We will release a long video generation model in the future.
> 
> Great! Can you give me the new inference for video generation large than 16 frames?

Just update your code, then run `bash sample/t2v.sh`.

**Comment by trongnk2106** [comment]
Thanks so much. But that repo Can generate video from images? I want to use generate video by image to improve from output t2v. I want to make video longer and highly quality. Thanks

**Comment by maxin-cn** [comment]
> Thanks so much. But that repo Can generate video from images? I want to use generate video by image to improve from output t2v. I want to make video longer and highly quality. Thanks



> Thanks so much. But that repo Can generate video from images? I want to use generate video by image to improve from output t2v. I want to make video longer and highly quality. Thanks

Thank you for your interest, but image-to-video is not currently supported.

**Comment by maxin-cn** [comment]
> Thanks so much. But that repo Can generate video from images? I want to use generate video by image to improve from output t2v. I want to make video longer and highly quality. Thanks

Thank you for your interest, but image-to-video is not currently supported.

**Comment by trongnk2106** [comment]
Oh, thank you so much.
