### ISSUE TITLE
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device

### ISSUE THREAD

**Issue by GeLink9999** [Vchitect/Latte#23]
HI I have successfully loaded t2v model using 
 bash sample/t2v.sh
but it shows the model is running on cpu, how to set it to run on GPU, thanks

Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.74it/s]
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Pipelines loaded with `dtype=torch.float16` cannot run with `cpu` device. It is not recommended to move them to `cpu` as running them will fail. Please make sure to use an accelerator to run the pipeline in inference, due to the lack of support for`float16` operations on this device in PyTorch. Please, remove the `torch_dtype=torch.float16` argument, or use another device for inference.
Processing the (Yellow and black tropical fish dart through the sea.) prompt

**Comment by GeLink9999** [comment]
It seems cuda is not available. I will check it, thanks

**Comment by wuleibegreat** [comment]
I have the same problem. Have you solved it

**Comment by GeLink9999** [comment]
You can try to change your pytorch-cup to pytorch-cuda.
