### ISSUE TITLE
 run bash sample/t2v.sh,but why?

### ISSUE THREAD

**Issue by liwei0826** [Vchitect/Latte#24]
try generating videos from text，why?
![image](https://github.com/Vchitect/Latte/assets/48194881/3d23fcb6-5848-4a66-89be-d2e4ce5a34f3)

https://github.com/Vchitect/Latte/assets/48194881/402b169c-b78d-4c7a-ac27-a3ea80b90fe5

**Comment by maxin-cn** [comment]
> try generating videos from text，why? ![image](https://private-user-images.githubusercontent.com/48194881/307202943-3d23fcb6-5848-4a66-89be-d2e4ce5a34f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTUzMTAsIm5iZiI6MTcwODY1NTAxMCwicGF0aCI6Ii80ODE5NDg4MS8zMDcyMDI5NDMtM2QyM2ZjYjYtNTg0OC00YTY2LTg5YmUtZDJlNGNlNWEzNGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDAyMjMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMGUxYWQ0Y2E3MmQ0YTliMjQxMjk1Yjk2MDE5MmRhMzJhYmE1Nzc4ZmJhNDEzODFhMGMzNWE4M2UwZDRjNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w5Mt_KiVL7A9tiRT9BvrzjeYKv0fy3QxoFdefV-w3GU)
> 
>  t2vA_dog_in_astronaut_suit_and_sunglasses_floating_in_space._0000webv-imageio.mp4

Hi, I just tested my code and the t2v model did not produce the quality video as you showed. Could you please check your code or pull down the code again? Thank you for your interest.

https://github.com/Vchitect/Latte/assets/38418898/3102b7c8-8beb-41cb-a582-a8f0caff08ee
