### ISSUE TITLE
T2V with >16 vedio_length output random noises

### ISSUE THREAD

**Issue by jeffchy** [Vchitect/Latte#25]
As the title.

Does it mean the current t2v model is not trained on other frame lengths and cannot generalize to other frame length?

**Comment by maxin-cn** [comment]
> As the title.
> 
> Does it mean the current t2v model is not trained on other frame lengths and cannot generalize to other frame length?

Hi, producing videos directly with more than 16 frames can lead to low-quality output. To generate videos longer than 16 frames, you might consider using the autoregressive mode for better results.

**Comment by jeffchy** [comment]
Thanks for your answer

**Comment by theweilu** [comment]
Hi, how can I turn on the autoregressive mode?
