### ISSUE TITLE
Excellent work, will there be an official support of images to vedio (like sora) ?

### ISSUE THREAD

**Issue by jeffchy** [Vchitect/Latte#26]
And the t2v model cannot recognize Chinese prompts

**Comment by maxin-cn** [comment]
> And the t2v model cannot recognize Chinese prompts

We may consider adding support for image-to-video conversion in the future. Currently, we utilize T5 as our text encoder, which may not support Chinese. Thanks for your interest.

**Comment by chenxinli001** [comment]
@maxin-cn here,  "image-to-video conversion" means a generalizable i2v?

**Comment by maxin-cn** [comment]
> @maxin-cn here, "image-to-video conversion" means a generalizable i2v?

Sure!

**Comment by chenxinli001** [comment]
> > @maxin-cn here, "image-to-video conversion" means a generalizable i2v?
> 
> Sure!

Thx! Looking forward to it!
