### ISSUE TITLE
Latte的实时微信讨论组

### ISSUE THREAD

**Issue by akebest** [Vchitect/Latte#28]
我刚试跑了一下t2v demo，效果还是有一定的差距的
在想几个事情，
1、是不是加大训练量能够很大改善，极大缩小跟sora 的差距
2、素材怎么搞得更好质量，比如类似dalle e 视频生成文字。

有没有实时的讨论组啊，比如微信群啥的，要不我建个

![latte](https://github.com/Vchitect/Latte/assets/135005135/ee2b27f3-eb5a-4205-b557-19eed4ec89bb)

**Comment by maxin-cn** [comment]
> 我刚试跑了一下t2v demo，效果还是有一定的差距的 在想几个事情， 1、是不是加大训练量能够很大改善，极大缩小跟sora 的差距 2、素材怎么搞得更好质量，比如类似dalle e 视频生成文字。
> 
> 有没有实时的讨论组啊，比如微信群啥的，要不我建个
> 
> ![latte](https://private-user-images.githubusercontent.com/135005135/307493902-ee2b27f3-eb5a-4205-b557-19eed4ec89bb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NTAwNjcsIm5iZiI6MTcwODc0OTc2NywicGF0aCI6Ii8xMzUwMDUxMzUvMzA3NDkzOTAyLWVlMmIyN2YzLWViNWEtNDIwNS1iNTU3LTE5ZWVkNGVjODliYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQwNDQyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDcxODU3OWI0ZjQzNmNhOGEzZmU0M2IxOWQ3OTY5OWU2N2M2YTI2ZGZmNDlmZWIzYjUzMDI1ZDQ4YTU4MWRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EvuMoLlR6H2J6vaNZNyh52XiSsu2he4pZc8VTq3HIkw)

Thank you for your interest and suggestions. I created a discord [channel](https://discord.gg/F9FXeusu) for discussion. Look forward to communicating with you to make the performance of LatteT2V model better ~

**Comment by uniqzheng** [comment]
二维码过期了，求加入讨论群

**Comment by pokameng** [comment]
二维码过期了，求加入讨论群

**Comment by matianyun** [comment]
discord channel cannot be used and the QR code is out of date.

**Comment by maxin-cn** [comment]
> discord channel cannot be used and the QR code is out of date.

Use this: https://discord.gg/RguYqhVU92

**Comment by matianyun** [comment]
Thank you for your quick reply! Can you respond to my discord question?
