### ISSUE TITLE
Does Latte support multiple GPUs

### ISSUE THREAD

**Issue by afezeriaWrnbbmm** [Vchitect/Latte#29]
Does Latte support multiple GPUs, and if so, how should it be set up?

**Comment by maxin-cn** [comment]
> Does Latte support multiple GPUs, and if so, how should it be set up?

Hi, I'm not sure what you mean by multi-GPU? Do you mean multi-GPU training or multi-GPU testing?

**Comment by afezeriaWrnbbmm** [comment]
I followed the steps in the readme to generate videos from text, but only one of my GPUs was used.
(base) root@nvidia3090:/home/nvidia3090# nvidia-smi
Sat Feb 24 07:13:27 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        Off | 00000000:04:00.0 Off |                  N/A |
|  0%   24C    P2             349W / 350W |  21275MiB / 24576MiB |    100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 3090        Off | 00000000:06:00.0 Off |                  N/A |
|  0%    5C    P8              28W / 350W |   2788MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce RTX 3090        Off | 00000000:07:00.0 Off |                  N/A |
|  0%    5C    P8              24W / 350W |   2770MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce RTX 3090        Off | 00000000:0C:00.0 Off |                  N/A |
|  0%    5C    P8              20W / 370W |   2786MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   4  NVIDIA GeForce RTX 3090        Off | 00000000:0D:00.0 Off |                  N/A |
|  0%    4C    P8              20W / 350W |   2776MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   5  NVIDIA GeForce RTX 3090        Off | 00000000:0E:00.0 Off |                  N/A |
|  0%    4C    P8              24W / 420W |   2786MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A   1210829      C   python                                     2810MiB |
|    0   N/A  N/A   1355236      C   python                                    18456MiB |
|    1   N/A  N/A   1210766      C   python                                     2782MiB |
|    2   N/A  N/A   1210696      C   python                                     2764MiB |
|    3   N/A  N/A   1210629      C   python                                     2780MiB |
|    4   N/A  N/A   1210479      C   python                                     2770MiB |
|    5   N/A  N/A   1210343      C   python                                     2780MiB |
+---------------------------------------------------------------------------------------+

**Comment by maxin-cn** [comment]
> I followed the steps in the readme to generate videos from text, but only one of my GPUs was used. (base) root@nvidia3090:/home/nvidia3090# nvidia-smi Sat Feb 24 07:13:27 2024 +---------------------------------------------------------------------------------------+ | NVIDIA-SMI 535.154.05 Driver Version: 535.154.05 CUDA Version: 12.2 | |-----------------------------------------+----------------------+----------------------+ | GPU Name Persistence-M | Bus-Id Disp.A | Volatile Uncorr. ECC | | Fan Temp Perf Pwr:Usage/Cap | Memory-Usage | GPU-Util Compute M. | | | | MIG M. | |=========================================+======================+======================| | 0 NVIDIA GeForce RTX 3090 Off | 00000000:04:00.0 Off | N/A | | 0% 24C P2 349W / 350W | 21275MiB / 24576MiB | 100% Default | | | | N/A | +-----------------------------------------+----------------------+----------------------+ | 1 NVIDIA GeForce RTX 3090 Off | 00000000:06:00.0 Off | N/A | | 0% 5C P8 28W / 350W | 2788MiB / 24576MiB | 0% Default | | | | N/A | +-----------------------------------------+----------------------+----------------------+ | 2 NVIDIA GeForce RTX 3090 Off | 00000000:07:00.0 Off | N/A | | 0% 5C P8 24W / 350W | 2770MiB / 24576MiB | 0% Default | | | | N/A | +-----------------------------------------+----------------------+----------------------+ | 3 NVIDIA GeForce RTX 3090 Off | 00000000:0C:00.0 Off | N/A | | 0% 5C P8 20W / 370W | 2786MiB / 24576MiB | 0% Default | | | | N/A | +-----------------------------------------+----------------------+----------------------+ | 4 NVIDIA GeForce RTX 3090 Off | 00000000:0D:00.0 Off | N/A | | 0% 4C P8 20W / 350W | 2776MiB / 24576MiB | 0% Default | | | | N/A | +-----------------------------------------+----------------------+----------------------+ | 5 NVIDIA GeForce RTX 3090 Off | 00000000:0E:00.0 Off | N/A | | 0% 4C P8 24W / 420W | 2786MiB / 24576MiB | 0% Default | | | | N/A | +-----------------------------------------+----------------------+----------------------+
> 
> +---------------------------------------------------------------------------------------+ | Processes: | | GPU GI CI PID Type Process name GPU Memory | | ID ID Usage | |=======================================================================================| | 0 N/A N/A 1210829 C python 2810MiB | | 0 N/A N/A 1355236 C python 18456MiB | | 1 N/A N/A 1210766 C python 2782MiB | | 2 N/A N/A 1210696 C python 2764MiB | | 3 N/A N/A 1210629 C python 2780MiB | | 4 N/A N/A 1210479 C python 2770MiB | | 5 N/A N/A 1210343 C python 2780MiB | +---------------------------------------------------------------------------------------+

The code that generates videos from texts does not currently support the multi-GPU parallel mode. If you want to generate video on multiple Gpus, please refer to  [sample_ddp.py](https://github.com/Vchitect/Latte/blob/main/sample/sample_ddp.py) to modify your code.

**Comment by afezeriaWrnbbmm** [comment]
Thanks for your answer
