### ISSUE TITLE
Where is the paper?

### ISSUE THREAD

**Issue by howardgriffin** [Vchitect/Latte#3]
Sorry to bother you again, but where can I find the paper . The paper link in the project seems invalid.

**Comment by maxin-cn** [comment]
> Sorry to bother you again, but where can I find the paper . The paper link in the project seems invalid.

Please wait for about 2 days. If it is available, I will let you know.

**Comment by maxin-cn** [comment]
> > Sorry to bother you again, but where can I find the paper . The paper link in the project seems invalid.
> 
> Please wait for about 2 days. If it is available, I will let you know.

I have updated the paper link in Readme.
