### ISSUE TITLE
What is 

### ISSUE THREAD

**Issue by olliacc** [Vchitect/Latte#30]
I'm asking for the lowest amount of GPU video memory (VRAM) necessary to run latte video generation effectively? for both training and inference.

**Comment by maxin-cn** [comment]
> I'm asking for the lowest amount of GPU video memory (VRAM) necessary to run latte video generation effectively? for both training and inference.

Hi, thanks for your interest. Inferencing one video on the A100 requires 20916MiB of GPU memory under fp16 precision mode. As for the GPU memory requirement of training, I think it may be dependent on your batch size.

**Comment by chenxinli001** [comment]
@maxin-cn 
May i set the local bz=1 for training latte on my own dataset? I mean, I heard that the enough batchsize seems to be key for the training of diffusion.
![image](https://github.com/Vchitect/Latte/assets/58136000/277e2311-9d49-463b-aebd-b4789f5ce79f)

Hi, you can set `batchsize` as 1. But I'm not sure if this will slow down performance. You can try it first. Looking forward to your feedback later~
