### ISSUE TITLE
Discriminative tasks

### ISSUE THREAD

**Issue by bhack** [Vchitect/Latte#32]
Have you tested your arch on discriminative tasks like Video/Panoptic segmentation?
There was some promising effort recently but on images:
https://github.com/cp3wan/DFormer

**Comment by maxin-cn** [comment]
> Have you tested your arch on discriminative tasks like Video/Panoptic segmentation? There was some promising effort recently but on images: https://github.com/cp3wan/DFormer

Thank you for your interest. We mainly tested our structure on the task of Video generation, and no Video/Panoptic segmentation tasks have been tested so far.
