### ISSUE TITLE
Re-implementation err on ffs experiment

### ISSUE THREAD

**Issue by dummy702** [Vchitect/Latte#36]
Good job, but I have some questions on ffs ckpt inference experiment.
1）I set "ckpt" in ffs.sh to the folder related to https://huggingface.co/maxin-cn/Latte/blob/main/ffs.pt", set "pretrained_model_path" to the folder related to https://huggingface.co/maxin-cn/Latte/tree/main/vae. 
But the performance of video generation is bad. Is there anything wrong with my process?

https://github.com/Vchitect/Latte/assets/161445238/1fcc2c49-402e-4977-9684-6547ac0e17bc

2）Besides, I edit the code in sample.py. If I keep the code "samples = vae.decode(samples / 0.18215).sample", I will get "Segmentation fault". Therefore, I replace the code with the following. Is there anything wrong with my process?
![截屏2024-02-27 下午5 14 47](https://github.com/Vchitect/Latte/assets/161445238/31d65eeb-41d1-4967-b166-8e95e76af773)

**Comment by maxin-cn** [comment]
> Good job, but I have some questions on ffs ckpt inference experiment. 1）I set "ckpt" in ffs.sh to the folder related to https://huggingface.co/maxin-cn/Latte/blob/main/ffs.pt", set "pretrained_model_path" to the folder related to https://huggingface.co/maxin-cn/Latte/tree/main/vae. But the performance of video generation is bad. Is there anything wrong with my process?
> 
>  sample.mp4 
> 2）Besides, I edit the code in sample.py. If I keep the code "samples = vae.decode(samples / 0.18215).sample", I will get "Segmentation fault". Therefore, I replace the code with the following. Is there anything wrong with my process? ![截屏2024-02-27 下午5 14 47](https://private-user-images.githubusercontent.com/161445238/308107375-31d65eeb-41d1-4967-b166-8e95e76af773.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMzUyMjMsIm5iZiI6MTcwOTAzNDkyMywicGF0aCI6Ii8xNjE0NDUyMzgvMzA4MTA3Mzc1LTMxZDY1ZWViLTQxZDEtNDk2Ny1iMTY2LThlOTVlNzZhZjc3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxMTU1MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmVkYTZiMzk0ZmJhYThmYWE3MThmZDc2NTQyZDJmYWI2NDhhYjMxZGJmNGFhZjYyOTA0MzgzOGQ2ODYzZmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SKtwSWjAVnCslDHkIYpuSVAtNdfKgbPPYYbb1vlGUEg)

I just tested my code and didn't find anything unusual. For the second question, perhaps you could reinstall your environment? Thanks for your interest.

https://github.com/Vchitect/Latte/assets/38418898/bbe200ea-3e25-4835-b726-b3201601cf36
