### ISSUE TITLE
Can you provide the code for DDIM sampler

### ISSUE THREAD

**Issue by lcwLcw123** [Vchitect/Latte#37]
I try to change the ‘sample_method’ hyperparamter to 'DDIM' in Latte/configs/t2v/t2v_sample.yaml, which make the bad performance of the output image. can you provide some scripts for DDIM sampler, or is that model can not work well when using DDIM sampler?

Sicnerely

**Comment by maxin-cn** [comment]
> I try to change the ‘sample_method’ hyperparamter to 'DDIM' in Latte/configs/t2v/t2v_sample.yaml, which make the bad performance of the output image. can you provide some scripts for DDIM sampler, or is that model can not work well when using DDIM sampler?
> 
> Sicnerely

I will provide the DDIM sampling method in the future, but I am not sure when it will be ready. If you already have a handle on DDIM's sampling method, welcome to PR.

I have solved the problem of not being able to generate video when using DDIM (https://github.com/Vchitect/Latte/commit/40c2e40fbb82ca92c93cd85d6790a6760e9fad30).
