### ISSUE TITLE
Issue about "LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by kaiw7** [Vchitect/Latte#38]
Hi, I would like to run bash sample/ucf101.sh for sampling but I met this "LayerNormKernelImpl" not implemented for 'Half'. Could you give some insights about how to resolve it? Many thanks.

**Comment by maxin-cn** [comment]
> Hi, I would like to run bash sample/ucf101.sh for sampling but I met this "LayerNormKernelImpl" not implemented for 'Half'. Could you give some insights about how to resolve it? Many thanks.

Hi, thanks for your interest. I did not find the function `LayerNormKernelImpl` in Latte. Could you provide more information?

**Comment by kaiw7** [comment]
> > Hi, I would like to run bash sample/ucf101.sh for sampling but I met this "LayerNormKernelImpl" not implemented for 'Half'. Could you give some insights about how to resolve it? Many thanks.
> 
> Hi, thanks for your interest. I did not find the function `LayerNormKernelImpl` in Latte. Could you provide more information?

Hi, it seems that this issue is caused by the environment. After I install the environment based on your environment.yaml, it seems that the pytorch version is not GPU version. Could you check the environment file again? Many thanks
<img width="793" alt="image" src="https://github.com/Vchitect/Latte/assets/124801863/2cb35b5b-b3bc-4aec-ab8e-76566e894f6a">

**Comment by maxin-cn** [comment]
> > > Hi, I would like to run bash sample/ucf101.sh for sampling but I met this "LayerNormKernelImpl" not implemented for 'Half'. Could you give some insights about how to resolve it? Many thanks.
> > 
> > 
> > Hi, thanks for your interest. I did not find the function `LayerNormKernelImpl` in Latte. Could you provide more information?
> 
> Hi, it seems that this issue is caused by the environment. After I install the environment based on your environment.yaml, it seems that the pytorch version is not GPU version. Could you check the environment file again? Many thanks <img alt="image" width="793" src="https://private-user-images.githubusercontent.com/124801863/309010499-2cb35b5b-b3bc-4aec-ab8e-76566e894f6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTgxMTIsIm5iZiI6MTcwOTI5NzgxMiwicGF0aCI6Ii8xMjQ4MDE4NjMvMzA5MDEwNDk5LTJjYjM1YjViLWIzYmMtNGFlYy1hYjhlLTc2NTY2ZTg5NGY2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQxMjU2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmU4ZDQ0YmE0OWE4ZGNkMDhhN2IwZDA4YjYzYWNmOTU4NGNmMzgzYjYyMmZiZmY3MmNkNjllZjczY2IxNTMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PomVxotHSwY6Kg7hUylUBKAKBcfQio3TTlsnY5jHNQU">

I used the installation method recommended by `pytorch`.
![image](https://github.com/Vchitect/Latte/assets/38418898/7cb489a9-1c9f-4da9-831d-7917466ce6f8)

If you still have environmental problems, please install as recommended by Pytorch.

**Comment by RuslanPeresy** [comment]
First, you need to install pytorch for your CUDA version - in the `environment.yml` CUDA version 11.7 is hardcoded.
For example, if you have CUDA 12.1:
`conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia`

Then, the bash script `sample/ucf101.sh` exports hardcoded `CUDA_VISIBLE_DEVICES=7`. Check your GPU index(es) using `nvidia-smi` command, and change the number if needed.

**Comment by kaiw7** [comment]
Hi, thanks, I solved it.

**Comment by likeatingcake** [comment]
> 首先，您需要为您的 CUDA 版本安装 pytorch - 在`environment.yml`CUDA 版本 11.7 中是硬编码的。 例如，如果您有 CUDA 12.1： `conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia`
> 
> 然后，bash 脚本`sample/ucf101.sh`导出硬编码的`CUDA_VISIBLE_DEVICES=7`。使用命令检查您的 GPU 索引`nvidia-smi`，并根据需要更改数字。

If my CUDA version is 9.1, does it mean I cannot run this project?

**Comment by likeatingcake** [comment]
My CUDA version is 11.7, but the error still persists after running.
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'
Is there a possibility of other reasons?
