### ISSUE TITLE
为什么会这样报错呢在运行sample.py模块的时候Traceback (most recent call last):   File "C:\Users\Dell\Desktop\Project\Latte-main\sample\sample.py", line 29, in <module>     from models import get_models   File "C:\Users\Dell\Desktop\Project\Latte-main\models\__init__.py", line 7, in <module>     from .latte_t2v import LatteT2V   File "C:\Users\Dell\Desktop\Project\Latte-main\models\latte_t2v.py", line 11, in <module>     from diffusers.models.embeddings import get_1d_sincos_pos_embed_from_grid, ImagePositionalEmbeddings, CaptionProjection, PatchEmbed, CombinedTimestepSizeEmbeddings ImportError: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings'

### ISSUE THREAD

**Issue by counwakd** [Vchitect/Latte#41]
Traceback (most recent call last):
  File "C:\Users\Dell\Desktop\Project\Latte-main\sample\sample.py", line 29, in <module>
    from models import get_models
  File "C:\Users\Dell\Desktop\Project\Latte-main\models\__init__.py", line 7, in <module>
    from .latte_t2v import LatteT2V
  File "C:\Users\Dell\Desktop\Project\Latte-main\models\latte_t2v.py", line 11, in <module>
    from diffusers.models.embeddings import get_1d_sincos_pos_embed_from_grid, ImagePositionalEmbeddings, CaptionProjection, PatchEmbed, CombinedTimestepSizeEmbeddings
ImportError: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings'

**Comment by maxin-cn** [comment]
> Traceback (most recent call last): File "C:\Users\Dell\Desktop\Project\Latte-main\sample\sample.py", line 29, in from models import get_models File "C:\Users\Dell\Desktop\Project\Latte-main\models__init__.py", line 7, in from .latte_t2v import LatteT2V File "C:\Users\Dell\Desktop\Project\Latte-main\models\latte_t2v.py", line 11, in from diffusers.models.embeddings import get_1d_sincos_pos_embed_from_grid, ImagePositionalEmbeddings, CaptionProjection, PatchEmbed, CombinedTimestepSizeEmbeddings ImportError: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings'

Hi, please check your diffusion version.
