### ISSUE TITLE
How can I turn on the autoregressive mode to generate >16 frame videos?

### ISSUE THREAD

**Issue by theweilu** [Vchitect/Latte#42]
> As the title.
> 
> Does it mean the current t2v model is not trained on other frame lengths and cannot generalize to other frame length?

Hi, producing videos directly with more than 16 frames can lead to low-quality output. To generate videos longer than 16 frames, you might consider using the autoregressive mode for better results.

_Originally posted by @maxin-cn in https://github.com/Vchitect/Latte/issues/25#issuecomment-1960887682_

**Comment by maxin-cn** [comment]
> ```
>           > As the title.
> ```
> 
> > Does it mean the current t2v model is not trained on other frame lengths and cannot generalize to other frame length?
> 
> Hi, producing videos directly with more than 16 frames can lead to low-quality output. To generate videos longer than 16 frames, you might consider using the autoregressive mode for better results.
> 
> _Originally posted by @maxin-cn in [#25 (comment)](https://github.com/Vchitect/Latte/issues/25#issuecomment-1960887682)_

Latte should not directly support autoregressive generation modes. You can consider using the method presented in [FreeNoise](https://arxiv.org/abs/2310.15169v3).
