### ISSUE TITLE
how to get 2048 videos for computing FVD?

### ISSUE THREAD

**Issue by hdjsjyl** [Vchitect/Latte#43]
Hi author,
    Thanks for your great work. 
    I would like to know how to get 2048 videos for computing FVD? Thanks

**Comment by maxin-cn** [comment]
> Hi author, Thanks for your great work. I would like to know how to get 2048 videos for computing FVD? Thanks

Just run `bash sample/ffs_ddp.sh` or `bash sample/ffs_ddp.sh`.

**Comment by hdjsjyl** [comment]
Hi @maxin-cn ,
    Thanks for your reply. My questions is how to get corresponding 2048 ground truth data, not generated data. 
    In this paper, it says 2048 real videos with 16 frames. I am not sure about how to get it. Any help is appreciated, thanks

**Comment by maxin-cn** [comment]
> Hi @maxin-cn , Thanks for your reply. My questions is how to get corresponding 2048 ground truth data, not generated data. In this paper, it says 2048 real videos with 16 frames. I am not sure about how to get it. Any help is appreciated, thanks

You can randomly sample 2048 videos from the real dataset or also use the entire real videos to calculate FVD.
