### ISSUE TITLE
Code Reuse

### ISSUE THREAD

**Issue by LinB203** [Vchitect/Latte#44]
Hi, thanks for your great work, your code and ablation experiments have inspired us a lot. Is it possible for me to make modifications based on your code to adapt it to [Open-Sora Plan](https://github.com/PKU-YuanGroup/Open-Sora-Plan)? Thank you.

**Comment by maxin-cn** [comment]
> Hi, thanks for your great work, your code and ablation experiments have inspired us a lot. Is it possible for me to make modifications based on your code to adapt it to [Open-Sora Plan](https://github.com/PKU-YuanGroup/Open-Sora-Plan)? Thank you.

Hi, thank you very much for your recognition of our work. You are welcome to use Latte's code. Please consider citing Latte's GitHub repository in the Acknowledgement section of the Open-Sora Plan.

**Comment by LinB203** [comment]
> > Hi, thanks for your great work, your code and ablation experiments have inspired us a lot. Is it possible for me to make modifications based on your code to adapt it to [Open-Sora Plan](https://github.com/PKU-YuanGroup/Open-Sora-Plan)? Thank you.
> 
> Hi, thank you very much for your recognition of our work. You are welcome to use Latte's code. Please consider citing Latte's GitHub repository in the Acknowledgement section of the Open-Sora Plan.

Great! Thanks!

**Comment by kabachuha** [comment]
I also wrote some practical ideas of how OpenSora/Latte can be improved with switching to Linear Transformers (e.g. ReBased). Please, check it out

https://github.com/PKU-YuanGroup/Open-Sora-Plan/issues/35

**Comment by wyhsirius** [comment]
@kabachuha Great, we will definitely check it! Thanks

**Comment by LinB203** [comment]
> > Hi, thanks for your great work, your code and ablation experiments have inspired us a lot. Is it possible for me to make modifications based on your code to adapt it to [Open-Sora Plan](https://github.com/PKU-YuanGroup/Open-Sora-Plan)? Thank you.
> 
> Hi, thank you very much for your recognition of our work. You are welcome to use Latte's code. Please consider citing Latte's GitHub repository in the Acknowledgement section of the Open-Sora Plan.

https://github.com/PKU-YuanGroup/Open-Sora-Plan/blob/main/README.md#acknowledgement
❤❤❤
[Latte](https://github.com/Vchitect/Latte): The **main codebase** we built upon and it is an wonderful video gererated model.
