### ISSUE TITLE
anyone meet zero grad?零梯度？

### ISSUE THREAD

**Issue by huangjch526** [Vchitect/Latte#45]
when I train latte on UCF101, the grad of linear layer are all zero. I think it is strange, 零梯度？

**Comment by maxin-cn** [comment]
> when I train latte on UCF101, the grad of linear layer are all zero. I think it is strange, 零梯度？

Hi, in Latte model initialization, we adopt the widely used [0](https://github.com/Vchitect/Latte/blob/70c5753d40e0791db20733a6958832bcf9623864/models/latte.py#L257) initialization, which may result in a relatively small gradient of the corresponding layer.
