### ISSUE TITLE
About evaluation 

### ISSUE THREAD

**Issue by kaiw7** [Vchitect/Latte#47]
HI, could you please share the script for evaluation like FVD?

**Comment by maxin-cn** [comment]
> HI, could you please share the script for evaluation like FVD?

Please refer to [stylegan-v](https://github.com/universome/stylegan-v).

**Comment by kaiw7** [comment]
Thank you very much. I have another question about what is difference between vae and sd-vae-ft (https://huggingface.co/maxin-cn/Latte/tree/main/sd-vae-ft-ema)? Which version of vae you used in Latte?

**Comment by maxin-cn** [comment]
> Thank you very much. I have another question about what is difference between vae and sd-vae-ft (https://huggingface.co/maxin-cn/Latte/tree/main/sd-vae-ft-ema)? Which version of vae you used in Latte?

Both vae can be used in Latte.
