### ISSUE TITLE
Train code of t2v？

### ISSUE THREAD

**Issue by kings-rgb** [Vchitect/Latte#48]
Do you have any plans to make the training t2v part of the code public? And the best model of T2V.

**Comment by maxin-cn** [comment]
> Do you have any plans to make the training t2v part of the code public? And the best model of T2V.

Hi, thanks for your interest. We currently have no plans to publicly release the training code for LatteT2V. We will release a better LatteT2V model as soon as possible.

**Comment by lyogavin** [comment]
you can try this one: https://github.com/lyogavin/train_your_own_sora

**Comment by fenghe12** [comment]
> you can try this one: https://github.com/lyogavin/train_your_own_sora
我遇到了一些问题 当使用此仓库时 您能提供一些解决办法吗

**Comment by maxin-cn** [comment]
> > you can try this one: https://github.com/lyogavin/train_your_own_sora
> > 我遇到了一些问题 当使用此仓库时 您能提供一些解决办法吗

What problems?

**Comment by fenghe12** [comment]
> > > you can try this one: https://github.com/lyogavin/train_your_own_sora
> > > 我遇到了一些问题 当使用此仓库时 您能提供一些解决办法吗
> 
> What problems?

您看下我发在哪个仓库里的 issue 推理的结果全是 0

**Comment by maxin-cn** [comment]
> > > > you can try this one: https://github.com/lyogavin/train_your_own_sora
> > > > 我遇到了一些问题 当使用此仓库时 您能提供一些解决办法吗
> > 
> > 
> > What problems?
> 
> 您看下我发在哪个仓库里的 issue 推理的结果全是 0

能够提供更多的信息么
