### ISSUE TITLE
如何复现主页展示的t2v效果？

### ISSUE THREAD

**Issue by HRain1016** [Vchitect/Latte#49]
非常棒的工作！请问复现主页展示的视频需要设置seed为多少或者还有别的设置项吗？每次跑出来的结果都不一样

**Comment by maxin-cn** [comment]
> 非常棒的工作！请问复现主页展示的视频需要设置seed为多少或者还有别的设置项吗？每次跑出来的结果都不一样


The generated videos are highly correlated with the seed used, but I haven't saved the seeds for these generation results displayed on the homepage.

**Comment by HRain1016** [comment]
> > 非常棒的工作！请问复现主页展示的视频需要设置seed为多少或者还有别的设置项吗？每次跑出来的结果都不一样
> 
> The generated videos are highly correlated with the seed used, but I haven't saved the seeds for these generation results displayed on the homepage.

Thanks for your response.

**Comment by HRain1016** [comment]
Can anyone else reproduce this? How is the seed set? Thanks for sharing!
