### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ucasyjz** [Vchitect/Latte#5]
ModuleNotFoundError: No module named 'petrel_client'，how can i solve this problem, pip seems to do not work

**Comment by maxin-cn** [comment]
> petrel_client

`petrel_client` is an SDK tool for storing files on cloud storage. You can comment out `petrel_client` directly and change its associated path to a local path. I will delete the codes related to `petrel_client` later.

**Comment by maxin-cn** [comment]
> ModuleNotFoundError: No module named 'petrel_client'，how can i solve this problem, pip seems to do not work

`petrel_client` is an SDK tool for storing files on cloud storage. You can comment out `petrel_client` directly and change its associated path to a local path. I will delete the codes related to `petrel_client` later.
