### ISSUE TITLE
Implementation of compression frame patch embedding (Fig. 3b)

### ISSUE THREAD

**Issue by paulchhuang** [Vchitect/Latte#52]
Hi, 
Thanks for the great work. I have a few questions:

1. By default which "patch embedding" is used? Fig.3(a) or (b)?
2. Is there a parameter to switch between (a) and (b) in a config file?
3. I'd like to take a look at the implementation of (b) -- compression frame patch embedding. I see `PatchEmbed` several places and they are from different libs: sometimes from diffuser sometimes from timm. Do you have a pointer to the code where Fig.3(b) is implemented?

**Comment by maxin-cn** [comment]
> Hi, Thanks for the great work. I have a few questions:
> 
> 1. By default which "patch embedding" is used? Fig.3(a) or (b)?
> 2. Is there a parameter to switch between (a) and (b) in a config file?
> 3. I'd like to take a look at the implementation of (b) -- compression frame patch embedding. I see `PatchEmbed` several places and they are from different libs: sometimes from diffuser sometimes from timm. Do you have a pointer to the code where Fig.3(b) is implemented?

1. Latte uses Fig.3 (a) by default.
2. This repo does not provide (b).
3.  Please refer to [here](https://github.com/mx-mark/VideoTransformer-pytorch/blob/194cae69722eb5efad031c59f4ff03bc60633fa8/video_transformer.py#L83).

**Comment by paulchhuang** [comment]
Thanks for the prompt reply and pointers.
