### ISSUE TITLE
diffusion noise modify

### ISSUE THREAD

**Issue by ErwinKC** [Vchitect/Latte#53]
Hi, it's a great job, hope you have time to answer my simple question, where can I modify the Gaussian noise parameter in the inference stage or sampling stage and if I change input to a image or video,  dose the model have ability to generate a video through this image or generate a awesome video though the existing poor quality video? Thanks

**Comment by maxin-cn** [comment]
> Hi, it's a great job, hope you have time to answer my simple question, where can I modify the Gaussian noise parameter in the inference stage or sampling stage and if I change input to a image or video, dose the model have ability to generate a video through this image or generate a awesome video though the existing poor quality video? Thanks

Thanks for your interest. 
LatteT2V is a pure text-to-video generation model that currently does not support image-to-video, nor can enhance the quality of input video.

You can change the Gaussian noise in [here](https://github.com/Vchitect/Latte/blob/9ededbe590a5439b6e7013d00fbe30e6c9b674b8/sample/pipeline_videogen.py#L502).
