### ISSUE TITLE
Extra key in ucf101.pt

### ISSUE THREAD

**Issue by wang-muhan** [Vchitect/Latte#56]
When I'm loading the pretrained ucf101 checkpoint, the error appears:
RuntimeError: Error(s) in loading state_dict for Latte:
        Unexpected key(s) in state_dict: "y_embedder.embedding_table.weight". 
All the other checkpoints can generate videos successfully, can you check this? Thank you

**Comment by maxin-cn** [comment]
> When I'm loading the pretrained ucf101 checkpoint, the error appears: RuntimeError: Error(s) in loading state_dict for Latte: Unexpected key(s) in state_dict: "y_embedder.embedding_table.weight". All the other checkpoints can generate videos successfully, can you check this? Thank you

Hi, can I confirm whether the extras parameter is 2 when you use the ucf101 pre-train model? See:
https://github.com/Vchitect/Latte/blob/9ededbe590a5439b6e7013d00fbe30e6c9b674b8/configs/ucf101/ucf101_sample.yaml#L14

**Comment by wang-muhan** [comment]
Sorry, I used 1 in the config file. Should I use 2?

**Comment by wang-muhan** [comment]
But your training code for ucf101 only support unconditional generation? Do you have the related code for class conditional generation to reproduce you results.

**Comment by wang-muhan** [comment]
Do you have pretrained models for unconditional generation?

**Comment by maxin-cn** [comment]
> Do you have pretrained models for unconditional generation?

All pre-trained models are unconditional generation except ucf101 and t2v.

**Comment by wang-muhan** [comment]
Thanks. How can I control the class being sampled, is it "sample_names" in the ucf101_sample.yaml? But I didn't found where you reference this value in your code

**Comment by maxin-cn** [comment]
> Thanks. How can I control the class being sampled, is it "sample_names" in the ucf101_sample.yaml? But I didn't found where you reference this value in your code

You can change the class label in here,
https://github.com/Vchitect/Latte/blob/9ededbe590a5439b6e7013d00fbe30e6c9b674b8/sample/sample.py#L90

**Comment by wang-muhan** [comment]
What's you training loss after converge? I want to reproduce but met some problem.

**Comment by maxin-cn** [comment]
> What's you training loss after converge? I want to reproduce but met some problem.

Training loss decreases quickly and oscillates around a value.
