### ISSUE TITLE
What is the difference between Latte and ViViT?

### ISSUE THREAD

**Issue by Leeeshuz** [Vchitect/Latte#59]
The architectures of Latte seem share the same idea with ViViT, what is the difference between Latte and ViViT?

**Comment by maxin-cn** [comment]
> The architectures of Latte seem share the same idea with ViViT, what is the difference between Latte and ViViT?

Hi, thanks for your interest. 
The main model architecture differences are:
1. We removed the CLS token. We believe that only using CLS token will lose the vast majority of information for the video generation task.
2. We have added an additional Variant 1 to the model design of Latte. We find that Variant 1 is better than the additional three variants under the same parameters.

**Comment by Leeeshuz** [comment]
I see. Some details are quite different. Thanks for your explanation!
