### ISSUE TITLE
FVD values of PVDM are strange

### ISSUE THREAD

**Issue by sihyun-yu** [Vchitect/Latte#6]
Hi, I am the first author of PVDM, and I just checked the FVD values of PVDM are much worse than the values that I reported in the paper. Could you tell me why such differences exist?

Many people tried (and succeeded) to reproduce the values, so it is weird to me.

**Comment by maxin-cn** [comment]
> Hi, I am the first author of PVDM, and I just checked the FVD values of PVDM are much worse than the values that I reported in the paper. Could you tell me why such differences exist?
> 
> Many people tried (and succeeded) to reproduce the values, so it is weird to me.

Hello, thanks for your interest of our work. For UCF101 and Skytimelapse datasets, we followed the paper and used provided pre-trained checkpoints for evaluation. However, we were unable to reproduce the reported results. It would be very helpful if you could provide any details or a complete evaluation code on how to obtain the results.

**Comment by sihyun-yu** [comment]
Just a quick check:
- Did you use ema weights?
- Did you use 2,048 samples for evaluation?
- Did you use 400 steps (DDPM sampler) for generating samples?

Because with this setup, I got many mails that the results can be reproduced with the checkpoints.

**Comment by sihyun-yu** [comment]
Hi,

there even exists a recent arxiv paper that has succeeded to reproduce the values of PVDM: https://arxiv.org/abs/2402.13729v1
If you face difficulties to reproduce the values, you should ask authors before making it public..

**Comment by sihyun-yu** [comment]
Can you please reply to this issue?

**Comment by maxin-cn** [comment]
> Can you please reply to this issue?

Thank you very much for sharing the info and sorry for missing your question. We will thoroughly review the results with the information you've provided. We would greatly appreciate any additional details you could offer regarding the reimplementation of your work. Many thanks again.
