### ISSUE TITLE
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by likeatingcake** [Vchitect/Latte#60]
`(latte) yueyc@super-AS-4124GS-TNR:~/Latte$ bash sample/ffs.sh
/home/yueyc/anaconda3/envs/latte/lib/python3.12/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Using Ema!
WARNING: using half percision for inferencing!
  0%|                                                                                                                                                           | 0/250 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/yueyc/Latte/sample/sample.py", line 141, in <module>
    main(omega_conf)
  File "/home/yueyc/Latte/sample/sample.py", line 108, in main
    samples = diffusion.p_sample_loop(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yueyc/Latte/diffusion/gaussian_diffusion.py", line 454, in p_sample_loop
    for sample in self.p_sample_loop_progressive(
  File "/home/yueyc/Latte/diffusion/gaussian_diffusion.py", line 505, in p_sample_loop_progressive
    out = self.p_sample(
          ^^^^^^^^^^^^^^
  File "/home/yueyc/Latte/diffusion/gaussian_diffusion.py", line 406, in p_sample
    out = self.p_mean_variance(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/yueyc/Latte/diffusion/respace.py", line 92, in p_mean_variance
    return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yueyc/Latte/diffusion/gaussian_diffusion.py", line 279, in p_mean_variance
    model_output = model(x, t, **model_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yueyc/Latte/diffusion/respace.py", line 130, in __call__
    return self.model(x, new_ts, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yueyc/Latte/models/latte.py", line 352, in forward
    x  = spatial_block(x, c)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/yueyc/anaconda3/envs/latte/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yueyc/anaconda3/envs/latte/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yueyc/Latte/models/latte.py", line 179, in forward
    x = x + gate_msa.unsqueeze(1) * self.attn(modulate(self.norm1(x), shift_msa, scale_msa))
                                                       ^^^^^^^^^^^^^
  File "/home/yueyc/anaconda3/envs/latte/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yueyc/anaconda3/envs/latte/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yueyc/anaconda3/envs/latte/lib/python3.12/site-packages/torch/nn/modules/normalization.py", line 201, in forward
    return F.layer_norm(
           ^^^^^^^^^^^^^
  File "/home/yueyc/anaconda3/envs/latte/lib/python3.12/site-packages/torch/nn/functional.py", line 2546, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

为何会出现这样的报错呢，求解答

**Comment by maxin-cn** [comment]
> `(latte) yueyc@super-AS-4124GS-TNR:~/Latte$ bash sample/ffs.sh /home/yueyc/anaconda3/envs/latte/lib/python3.12/site-packages/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead. torch.utils._pytree._register_pytree_node( Using Ema! WARNING: using half percision for inferencing! 0%| | 0/250 [00:00<?, ?it/s] Traceback (most recent call last): File "/home/yueyc/Latte/sample/sample.py", line 141, in main(omega_conf) File "/home/yueyc/Latte/sample/sample.py", line 108, in main samples = diffusion.p_sample_loop( ^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/yueyc/Latte/diffusion/gaussian_diffusion.py", line 454, in p_sample_loop for sample in self.p_sample_loop_progressive( File "/home/yueyc/Latte/diffusion/gaussian_diffusion.py", line 505, in p_sample_loop_progressive out = self.p_sample( ^^^^^^^^^^^^^^ File "/home/yueyc/Latte/diffusion/gaussian_diffusion.py", line 406, in p_sample out = self.p_mean_variance( ^^^^^^^^^^^^^^^^^^^^^ File "/home/yueyc/Latte/diffusion/respace.py", line 92, in p_mean_variance return super().p_mean_variance(self._wrap_model(model), *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/yueyc/Latte/diffusion/gaussian_diffusion.py", line 279, in p_mean_variance model_output = model(x, t, **model_kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/yueyc/Latte/diffusion/respace.py", line 130, in **call** return self.model(x, new_ts, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/yueyc/Latte/models/latte.py", line 352, in forward x = spatial_block(x, c) ^^^^^^^^^^^^^^^^^^^ File "/home/yueyc/anaconda3/envs/latte/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl return self._call_impl(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/yueyc/anaconda3/envs/latte/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl return forward_call(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/yueyc/Latte/models/latte.py", line 179, in forward x = x + gate_msa.unsqueeze(1) * self.attn(modulate(self.norm1(x), shift_msa, scale_msa)) ^^^^^^^^^^^^^ File "/home/yueyc/anaconda3/envs/latte/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl return self._call_impl(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/yueyc/anaconda3/envs/latte/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl return forward_call(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/yueyc/anaconda3/envs/latte/lib/python3.12/site-packages/torch/nn/modules/normalization.py", line 201, in forward return F.layer_norm( ^^^^^^^^^^^^^ File "/home/yueyc/anaconda3/envs/latte/lib/python3.12/site-packages/torch/nn/functional.py", line 2546, in layer_norm return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'
> 
> 为何会出现这样的报错呢，求解答

Please refer to https://github.com/Vchitect/Latte/issues/38.
