### ISSUE TITLE
Evaluate the FVD？

### ISSUE THREAD

**Issue by huangjch526** [Vchitect/Latte#65]
Hi, can I evaluate the FVD result of 59.82 in your paper on the SKY dataset? Can you release your code and parameters for evaluating FVD?

**Comment by maxin-cn** [comment]
> Hi, can I evaluate the FVD result of 59.82 in your paper on the SKY dataset? Can you release your code and parameters for evaluating FVD?

Please refer to https://github.com/universome/stylegan-v.

**Comment by huangjch526** [comment]
I used this code and the video generated by your pre-trained model to test the FVD, but I was only able to measure an FVD of 96.5, and could not reproduce the values of your paper. Can anyone teach me how to evaluate the FVD result of 59.82 in the paper on the SKY dataset?

**Comment by maxin-cn** [comment]
> I used this code and the video generated by your pre-trained model to test the FVD, but I was only able to measure an FVD of 96.5, and could not reproduce the values of your paper. Can anyone teach me how to evaluate the FVD result of 59.82 in the paper on the SKY dataset?

Could you provide some more details about your evaluation of FVD?

**Comment by huangjch526** [comment]
I generated 2048 16-frame videos with sample.sh using the provided pre-trained Latte checkpoint on sky, and then I converted the generated videos to frame-by-frame image format, followed by the stylegan-v/src/scripts/calc_metrics_for_dataset.py code in stylegan-v , I set the real video dir to be the image format of the sky dataset and set the fake video dir to be the image format of the video I generated. In calc_metrics_for_dataset.py I use the recommended default parameters from its readme. I choose to measure the metrics fvd2048_16f.

**Comment by maxin-cn** [comment]
> I generated 2048 16-frame videos with sample.sh using the provided pre-trained Latte checkpoint on sky, and then I converted the generated videos to frame-by-frame image format, followed by the stylegan-v/src/scripts/calc_metrics_for_dataset.py code in stylegan-v , I set the real video dir to be the image format of the sky dataset and set the fake video dir to be the image format of the video I generated. In calc_metrics_for_dataset.py I use the recommended default parameters from its readme. I choose to measure the metrics fvd2048_16f.

Maybe you can adjust this [parameter](https://github.com/universome/stylegan-v/blob/3fecd69c602e1cda204357201461c0fb0a634909/src/metrics/frechet_video_distance.py#L27C44-L27C60) to match the training sample interval.
