### ISSUE TITLE
FaceForensics数据集

### ISSUE THREAD

**Issue by likeatingcake** [Vchitect/Latte#67]
现在好像无法下载FaceForensics数据集，只可以下载FaceForensics++，请问使用FaceForensics++训练模型可以吗

**Comment by maxin-cn** [comment]
> 现在好像无法下载FaceForensics数据集，只可以下载FaceForensics++，请问使用FaceForensics++训练模型可以吗

You can use any dataset you want. However, if you want to replace FaceForensics with Faceforensics ++, I'm not so sure the two datasets are the same.

**Comment by ShunLu91** [comment]
> 现在好像无法下载FaceForensics数据集，只可以下载FaceForensics++，请问使用FaceForensics++训练模型可以吗

I have consulted the organization of FaceForensics. After application, you can download the FaceForensics using '—server EU2 flag' from the script of FaceForensics++, i.e. using the 'SERVER_URL' as below:
```python
SERVER_URL = 'http://kaldir.vc.in.tum.de/faceforensics/'
```

**Comment by maxin-cn** [comment]
You now download FFS at [here](https://huggingface.co/datasets/maxin-cn/FaceForensics/tree/main).
