### ISSUE TITLE
Questions about the *0.18215 and /0.18215 operation

### ISSUE THREAD

**Issue by haibao-yu** [Vchitect/Latte#72]
Hi, thanks for your excellent work. 
I wonder to know the meaning of mul_(0.18215) and if we can remove this operation in following command
https://github.com/Vchitect/Latte/blob/c456dff74150e5b0db305fdd86b6f6de155c7634/train.py#L208

Looking forward to your reply.

**Comment by maxin-cn** [comment]
> Hi, thanks for your excellent work. I wonder to know the meaning of mul_(0.18215) and if we can remove this operation in following command
> 
> https://github.com/Vchitect/Latte/blob/c456dff74150e5b0db305fdd86b6f6de155c7634/train.py#L208
> 
> Looking forward to your reply.

Hi, thanks for your interest. This operation (* and / 0.18215) inherits from stable diffusion. Removing this operation may result in poor results. You can refer to https://github.com/huggingface/diffusers/issues/726.

**Comment by haibao-yu** [comment]
> > Hi, thanks for your excellent work. I wonder to know the meaning of mul_(0.18215) and if we can remove this operation in following command
> > https://github.com/Vchitect/Latte/blob/c456dff74150e5b0db305fdd86b6f6de155c7634/train.py#L208
> > 
> > Looking forward to your reply.
> 
> Hi, thanks for your interest. This operation (* and / 0.18215) inherits from stable diffusion. Removing this operation may result in poor results. You can refer to [huggingface/diffusers#726](https://github.com/huggingface/diffusers/issues/726).

Thanks for your prompt reply.
