### ISSUE TITLE
有关时长的问题。

### ISSUE THREAD

**Issue by LinQianhe02grey** [Vchitect/Latte#74]
您好，很感谢您的工作。我想请问一下这个项目最长能生成多久的视频呢？我按照您的指引生成了两秒钟的视频，如果想要更长一点，我该如何操作呢？可能问的很小白，抱歉。再次感谢您的工作。

**Comment by LinQianhe02grey** [comment]
当我想生成只有1秒钟的视频，是否可以实现呢？

**Comment by maxin-cn** [comment]
> 当我想生成只有1秒钟的视频，是否可以实现呢？

目前最长可以生成2s 16帧的视频。如果你想生成1s 8帧的视频，可以尝试将时序上的绝对位置编码缩放为长度为8的向量。

**Comment by LinQianhe02grey** [comment]
好的，谢谢您的工作与答复。
