### ISSUE TITLE
question on t2v model training

### ISSUE THREAD

**Issue by diffusion-lover** [Vchitect/Latte#75]
Thanks for sharing a great work!

I found two folders for vae in t2v pretrained model: https://huggingface.co/maxin-cn/Latte/tree/main/t2v_required_models

1. vae
2. vae_temporal_decoder

It seems that t2v model uses the "vae_temporal_decoder" pretrained model for decoding latents.
The "vae" pretrained model is used to encode images when you train transformer network?

**Comment by maxin-cn** [comment]
> Thanks for sharing a great work!
> 
> I found two folders for vae in t2v pretrained model: https://huggingface.co/maxin-cn/Latte/tree/main/t2v_required_models
> 
> 1. vae
> 2. vae_temporal_decoder
> 
> It seems that t2v model uses the "vae_temporal_decoder" pretrained model for decoding latents. The "vae" pretrained model is used to encode images when you train transformer network?

Yes, that is right.
