### ISSUE TITLE
how to place and preprocess these datasets

### ISSUE THREAD

**Issue by renyuanzhe** [Vchitect/Latte#78]
FaceForensics, SkyTimelapse, UCF101, and Taichi-HD

**Comment by maxin-cn** [comment]
> FaceForensics, SkyTimelapse, UCF101, and Taichi-HD

You can refer to https://github.com/Vchitect/Latte/issues/35. If it's still not clear, I'll give you a data structure.

**Comment by renyuanzhe** [comment]
> > FaceForensics, SkyTimelapse, UCF101, and Taichi-HD
> 
> You can refer to #35. If it's still not clear, I'll give you a data structure.

should i write the preprocess code by myself, or is your repository contains the needed code?

**Comment by renyuanzhe** [comment]
and could you offer these datasets' structure in the project, I wonder if the structure is modified when preprocessing

**Comment by maxin-cn** [comment]
> and could you offer these datasets' structure in the project, I wonder if the structure is modified when preprocessing

All datasets have this dataset structure following their original structure, and no additional operations are required.

```
ROOT:
├── train
    ├── video1.mp4
    ├── video2.mp4
├── test
    ├── video1.mp4
    ├── video2.mp4
```

or

```
ROOT:
├── train
    ├── video1.mp4
        ├── frame_0001.png
        ├── frame_0002.png
    ├── video2.mp4
        ├── frame_0001.png
        ├── frame_0002.png
├── test
    ├── video1.mp4
        ├── frame_0001.png
        ├── frame_0002.png
    ├── video2.mp4
        ├── frame_0001.png
        ├── frame_0002.png
```

**Comment by renyuanzhe** [comment]
> > and could you offer these datasets' structure in the project, I wonder if the structure is modified when preprocessing
> 
> All datasets have this dataset structure following their original structure, and no additional operations are required.
> 
> ```
> ROOT:
> ├── train
>     ├── video1.mp4
>     ├── video2.mp4
> ├── test
>     ├── video1.mp4
>     ├── video2.mp4
> ```
> 
> or
> 
> ```
> ROOT:
> ├── train
>     ├── video1.mp4
>         ├── frame_0001.png
>         ├── frame_0002.png
>     ├── video2.mp4
>         ├── frame_0001.png
>         ├── frame_0002.png
> ├── test
>     ├── video1.mp4
>         ├── frame_0001.png
>         ├── frame_0002.png
>     ├── video2.mp4
>         ├── frame_0001.png
>         ├── frame_0002.png
> ```

thankyou, I have preprocessed the dataset.however I find that the input img size is 32 inthe code,this is different with 256 in the paper. Is there something wrong?

**Comment by maxin-cn** [comment]
> > > and could you offer these datasets' structure in the project, I wonder if the structure is modified when preprocessing
> > 
> > 
> > All datasets have this dataset structure following their original structure, and no additional operations are required.
> > ```
> > ROOT:
> > ├── train
> >     ├── video1.mp4
> >     ├── video2.mp4
> > ├── test
> >     ├── video1.mp4
> >     ├── video2.mp4
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or
> > ```
> > ROOT:
> > ├── train
> >     ├── video1.mp4
> >         ├── frame_0001.png
> >         ├── frame_0002.png
> >     ├── video2.mp4
> >         ├── frame_0001.png
> >         ├── frame_0002.png
> > ├── test
> >     ├── video1.mp4
> >         ├── frame_0001.png
> >         ├── frame_0002.png
> >     ├── video2.mp4
> >         ├── frame_0001.png
> >         ├── frame_0002.png
> > ```
> 
> thankyou, I have preprocessed the dataset.however I find that the input img size is 32 inthe code,this is different with 256 in the paper. Is there something wrong?

The encoder will downsample video from 256 to 32.
