### ISSUE TITLE
the code of variant 4

### ISSUE THREAD

**Issue by pangpangjy** [Vchitect/Latte#79]
Hi. Thanks for your great work! I am very interested in the variant 4 structure mentioned in your paper. Could you please release the code of this part?

**Comment by maxin-cn** [comment]
> Hi. Thanks for your great work! I am very interested in the variant 4 structure mentioned in your paper. Could you please release the code of this part?

Thank you for your interest. You can easily change the open-source Variant 1 to Variant 4. Please let me know if you encounter any problems.
