### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ucasyjz** [Vchitect/Latte#8]
Where is the transformer/config.json when sh t2v.sh

**Comment by maxin-cn** [comment]
> Where is the transformer/config.json when sh t2v.sh

Please download `scheduler`, `text_encoder`, `tokenizer`, `transformer`,  `vae`, and `model_index.json` from https://huggingface.co/PixArt-alpha/PixArt-XL-2-512x512/tree/main into one folder. As for `transformer`, only `config.json` is required.

**Comment by ucasyjz** [comment]
After I download, t2v can not generate the results as the demonstration, can you give me more help
