### ISSUE TITLE
How to get preprocessed_ffs

### ISSUE THREAD

**Issue by zhang-haojie** [Vchitect/Latte#82]
Hello author, thank you very much for your work. 

When I run `train_with_img.py`, I see that `preprocessed_ffs` in the dataset needs `images` and `train_list.txt`. I don't know how to process FFS to get these data. In addition, I use `original` in FFS instead of `videos`, is this correct? 

Thank you!

**Comment by maxin-cn** [comment]
> Hello author, thank you very much for your work.
> 
> When I run `train_with_img.py`, I see that `preprocessed_ffs` in the dataset needs `images` and `train_list.txt`. I don't know how to process FFS to get these data. In addition, I use `original` in FFS instead of `videos`, is this correct?
> 
> Thank you!

Thanks for your interest. This is the content of `train_list.txt` (video-name/frame.jpg):
![image](https://github.com/Vchitect/Latte/assets/38418898/fb3beb3c-ac58-490f-b6c6-dff31ec7417d)

Sorry, I'm not sure I understand what you mean by `original`. Could you please provide more information?

**Comment by zhang-haojie** [comment]
Thank you for your reply. I have downloaded the FFS dataset now. I would like to know if there is any preprocessing code available to generate the `preprocessed_ffs/train_list.txt` and `preprocessed_ffs/train/images/` in config. The FFS dataset I downloaded has three categories under `train`: `altered`, `mask` and `original`. I used `original` as the `preprocessed_ffs/train/videos/ `in config.

**Comment by maxin-cn** [comment]
Sorry for the late reply. Now you can download FFS at [here](https://huggingface.co/datasets/maxin-cn/FaceForensics).

**Comment by zhang-haojie** [comment]
Thank you very much!
