### ISSUE TITLE
Any plan to implement Latte in HuggingFace's diffusers library?

### ISSUE THREAD

**Issue by Quest4AiJ** [Vchitect/Latte#83]
@maxin-cn  Great to see your release of the updated LatteT2V model. Awesome work!

Do you have a plan to implement Latte in HuggingFace's diffusers library? As a reference, I am seeing a relevant community request about implementing Latte in diffusers at https://github.com/huggingface/diffusers/issues/7223

**Comment by maxin-cn** [comment]
> @maxin-cn Great to see your release of the updated LatteT2V model. Awesome work!
> 
> Do you have a plan to implement Latte in HuggingFace's diffusers library? As a reference, I am seeing a relevant community request about implementing Latte in diffusers at [huggingface/diffusers#7223](https://github.com/huggingface/diffusers/issues/7223)

Hi, thanks for your interest. I'm moving forward with this.

**Comment by wyhsirius** [comment]
@Quest4AiJ Thanks for asking, we are very interested. Could you please also let us know how to involve Latte in diffusers?

**Comment by maxin-cn** [comment]
Latte is integrated into [diffusers](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/transformers/latte_transformer_3d.py).

**Comment by Quest4AiJ** [comment]
Awesome!  This is a great move, @maxin-cn  

I saw you spent nearly one month to get it merged. Your effort will be definitely worth it. Thanks a lot
