### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ucasyjz** [Vchitect/Latte#9]
I have a question, after making the setting for t2v, run t2v.sh, the generation is all noise,

**Comment by maxin-cn** [comment]
> I have a question, after making the setting for t2v, run t2v.sh, the generation is all noise,

Hi, I have fixed the T2V sampling bug. There are two modifications: 
https://github.com/maxin-cn/Latte/blob/c11f0dba7d5f0e071f1b5d9b44dabf6d40dca733/sample/sample_t2v.py#L32
and
https://github.com/maxin-cn/Latte/blob/c11f0dba7d5f0e071f1b5d9b44dabf6d40dca733/download.py#L21

Please modify your codes.
