### ISSUE TITLE
Can Latte train for I2V tasks?

### ISSUE THREAD

**Issue by 0Godness** [Vchitect/Latte#90]
Thanks for your nice work! I want to know how to extend Latte to I2V tasks. Hoping for your reply!

**Comment by maxin-cn** [comment]
> Thanks for your nice work! I want to know how to extend Latte to I2V tasks. Hoping for your reply!

Hi, thanks for your interest. You can refer to our latest image animation (a.k.a, image-to-video generation) work [Cinemo](https://maxin.me/cinemo_project/).

**Comment by maxin-cn** [comment]
> > Thanks for your nice work! I want to know how to extend Latte to I2V tasks. Hoping for your reply!
> 
> Hi, thanks for your interest. We are working on it and you can refer to our latest image animation (a.k.a, image-to-video generation) work [Cinemo](https://maxin.me/cinemo_project/) and [SEINE](https://github.com/Vchitect/SEINE). The codes and checkpoints are also public.
