### ISSUE TITLE
what the param <input_sq_size> stands for?

### ISSUE THREAD

**Issue by leonardodora** [Vchitect/Latte#92]
And how should we use it in training and sampling?
Thanks!

**Comment by maxin-cn** [comment]
> And how should we use it in training and sampling? Thanks!

Could you please provide more information about this? I don't find this parameter in our repo.

**Comment by leonardodora** [comment]
> > And how should we use it in training and sampling? Thanks!
> 
> Could you please provide more information about this? I don't find this parameter in our repo.

So sorry, I ask the wrong place
