### ISSUE TITLE
Can we use batch_size>1 in sample_t2x.py

### ISSUE THREAD

**Issue by foreverpiano** [Vchitect/Latte#93]

**Comment by foreverpiano** [comment]
@maxin-cn @wyhsirius

**Comment by maxin-cn** [comment]
It should be, but I haven't tested it.

**Comment by foreverpiano** [comment]
@maxin-cn  I modify the sample_t2x.py with bs=4. It returns totally different picture for some prompt and slightly different comparing to bs=1. Is it strange?

**Comment by foreverpiano** [comment]
a minimum modification for test could be
```
for i in range(0, len(args.text_prompt), args.batch_size):
            batch_prompts = args.text_prompt[i:i+args.batch_size]
            print('Processing batch: {}'.format(batch_prompts))
```
replace
https://github.com/Vchitect/Latte/blob/main/sample/sample_t2x.py#L128C5-L140C40

**Comment by maxin-cn** [comment]
Based on your question description, would you like to generate the same multiple pictures simultaneously?

**Comment by foreverpiano** [comment]
No. I want to generate different image. Now I think it may be the torch.rand issue. The batch inference gets different random when generating latent

**Comment by maxin-cn** [comment]
Sure! The initial random Gaussian noise affects the generated results significantly even using the same prompt.
