### ISSUE TITLE
Evaluate the `FVD` on FFS

### ISSUE THREAD

**Issue by zhang-haojie** [Vchitect/Latte#94]
Thank you very much for your excellent work! 

I am using the [stylegan-v](https://github.com/universome/stylegan-v) to compute the `FVD` on the FFS Dataset. Following the tutorial, I generated 2048 videos with 16 frames each (`frame_interval=1`) and converted them to frames using `convert_videos_to_frames.py`. 

In a previous issue [#65](https://github.com/Vchitect/Latte/issues/65#issuecomment-2043988865) you mentioned modifying the `subsample_factor` of `compute_fvd` to to match the training `frame_interval` (`frame_interval=3` in training config). However, I encountered the following problem:

```
File "/data1/haojie_data/workspace/Video/stylegan-v/src/training/dataset.py", line 400, in __getitem__
    assert num_frames_available - self.load_n_consecutive * self.subsample_factor >= 0, f"We have only {num_frames_available} frames available, cannot load {self.load_n_consecutive} frames."
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: We have only 16 frames available, cannot load 16 frames.
```

Here are the metrics I obtained without modifying the `subsample_factor` (which is set to 1 by default):

```
{"results": {"fvd2048_16f": 133.67623789319404}, "metric": "fvd2048_16f", "total_time": 47.84211015701294, "total_time_str": "48s", "num_gpus": 1, "snapshot_pkl": null, "timestamp": 1720616283.5374413}
{"results": {"fid50k_full": 3.11848005879192}, "metric": "fid50k_full", "total_time": 657.8561081886292, "total_time_str": "10m 58s", "num_gpus": 1, "snapshot_pkl": null, "timestamp": 1720616941.3939197}
```

Could you please provide some suggestions? Thank you very much.

**Comment by maxin-cn** [comment]
Thanks for your interest.  Please only change the frame interval of the real dataset.

**Comment by zhang-haojie** [comment]
I tried to find out how to change the frame interval of the real dataset, but failed. I then looked at the structure of [stylegan-v](https://github.com/universome/stylegan-v) and found a possible reason: the total number of frames in one video I generated is 16, which might be the cause of the error. 

This is because in `dataset.py`, on line 400, there is a check: 

`assert num_frames_available - self.load_n_consecutive * self.subsample_factor >= 0`. 

`num_frames_available` is the total number of frames in one fake video (16 in sample config), and `self.load_n_consecutive` and `self.subsample_factor` are the `num_frames` and `subsample_factor` specified in [`compute_fvd`](https://github.com/universome/stylegan-v/blob/master/src/metrics/frechet_video_distance.py) (16 and 3 respectively). 

Can you give me some more suggestions? Thank you very much.

**Comment by maxin-cn** [comment]
Please change this https://github.com/universome/stylegan-v/blob/3fecd69c602e1cda204357201461c0fb0a634909/src/metrics/frechet_video_distance.py#L27

and keep this https://github.com/universome/stylegan-v/blob/3fecd69c602e1cda204357201461c0fb0a634909/src/metrics/frechet_video_distance.py#L40

**Comment by zhang-haojie** [comment]
I get it! thank you very much

**Comment by Owen-Kinggg** [comment]
I got the result : fvd2048_16f": 133.59441494256066. I may use the same config as you: frame interval= 1, 2048 video and 16 frame in FFS dataset.
The `realdata_subsample_factor: int=3`.

How do you solve this problem? Thanks





> Thank you very much for your excellent work!
> 
> I am using the [stylegan-v](https://github.com/universome/stylegan-v) to compute the `FVD` on the FFS Dataset. Following the tutorial, I generated 2048 videos with 16 frames each (`frame_interval=1`) and converted them to frames using `convert_videos_to_frames.py`.
> 
> In a previous issue [#65](https://github.com/Vchitect/Latte/issues/65#issuecomment-2043988865) you mentioned modifying the `subsample_factor` of `compute_fvd` to to match the training `frame_interval` (`frame_interval=3` in training config). However, I encountered the following problem:
> 
> ```
> File "/data1/haojie_data/workspace/Video/stylegan-v/src/training/dataset.py", line 400, in __getitem__
>     assert num_frames_available - self.load_n_consecutive * self.subsample_factor >= 0, f"We have only {num_frames_available} frames available, cannot load {self.load_n_consecutive} frames."
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AssertionError: We have only 16 frames available, cannot load 16 frames.
> ```
> 
> Here are the metrics I obtained without modifying the `subsample_factor` (which is set to 1 by default):
> 
> ```
> {"results": {"fvd2048_16f": 133.67623789319404}, "metric": "fvd2048_16f", "total_time": 47.84211015701294, "total_time_str": "48s", "num_gpus": 1, "snapshot_pkl": null, "timestamp": 1720616283.5374413}
> {"results": {"fid50k_full": 3.11848005879192}, "metric": "fid50k_full", "total_time": 657.8561081886292, "total_time_str": "10m 58s", "num_gpus": 1, "snapshot_pkl": null, "timestamp": 1720616941.3939197}
> ```
> 
> Could you please provide some suggestions? Thank you very much.
