### ISSUE TITLE
How can I utilize the weights of pre-trained PixArt-α to initialize the parameters of the spatial Transformer block in the Latte T2V model?

### ISSUE THREAD

**Issue by g-makerr** [Vchitect/Latte#95]
How can I utilize the weights of pre-trained PixArt-α to initialize the parameters of the spatial Transformer block in the Latte T2V model.

**Comment by maxin-cn** [comment]
You can use the weights of pre-trained PixArt-α to initialize [this part](https://github.com/Vchitect/Latte/blob/964d4330f8b7ce3e92e8495088766960b51fabe1/models/latte_t2v.py#L585) while making [the other part](https://github.com/Vchitect/Latte/blob/964d4330f8b7ce3e92e8495088766960b51fabe1/models/latte_t2v.py#L609) random initialization.

**Comment by g-makerr** [comment]
> You can use the weights of pre-trained PixArt-α to initialize [this part](https://github.com/Vchitect/Latte/blob/964d4330f8b7ce3e92e8495088766960b51fabe1/models/latte_t2v.py#L585) while making [the other part](https://github.com/Vchitect/Latte/blob/964d4330f8b7ce3e92e8495088766960b51fabe1/models/latte_t2v.py#L609) random initialization.

Thanks for your reply. I will try it.
