### ISSUE TITLE
Is there tutorial on transfering t2i to t2v model?

### ISSUE THREAD

**Issue by foreverpiano** [Vchitect/Latte#98]
An updated LatteT2V model initialized with the [PixArt-α](https://github.com/PixArt-alpha/PixArt-alpha) is released, the checkpoint can be found [here](https://huggingface.co/maxin-cn/Latte-0/tree/main/transformer).
I wonder how you get t2i model to t2v model. Is there any tutorial I can refer, on temporal time_embedding, dimension switching? 
@maxin-cn

**Comment by foreverpiano** [comment]
Some question：
1. how to choose time_embedding?
2. how to switch dimension?
3. how to initialized transformer layer of temporal from pixart, and what config.json needs to modify?
4. I see there are video and picture training, and what we keep from pixart weight?

**Comment by maxin-cn** [comment]
Hi, please refer to this issue (https://github.com/Vchitect/Latte/issues/95).

**Comment by foreverpiano** [comment]
thanks for solving Q4. Is there any suggestion on Q1 2 3? @maxin-cn

**Comment by maxin-cn** [comment]
Hi, thanks for your interest. 

I am not sure about Q1 and Q2. Could you please provide more details?

As for Q3, I think there's no need for any modification.
